version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pigeons_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.dump:/docker-entrypoint-initdb.d/backup.dump
    command: >
      sh -c "
      if [ -f /docker-entrypoint-initdb.d/backup.dump ]; then
        pg_restore -U $POSTGRES_USER -d $POSTGRES_DB /docker-entrypoint-initdb.d/backup.dump;
      fi
      "

  mailcatcher:
    image: dockage/mailcatcher
    container_name: mailcatcher
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres_data:
